### ISSUE TITLE
What is the timespan of the video slimelapse_extended.mv

### ISSUE THREAD

**Issue by ff6347** [topada/FHP-IO-galton-board-physarum#1]
Hi @topada can you remember what the timespan of this recording was? Based on the length of the video and the framerate I calculated something like 24hours is that right?
https://github.com/topada/FHP-IO-galton-board-physarum/blob/master/processing_sketch/slime_tracker/data/slimelapse_extended.mov

**Comment by topada** [comment]
Looking at the timestamps of the first and last frame it actually took about **103 h** (3 days 7 hours)

**Comment by ff6347** [comment]
Thanks. So I was totally wrong. :-) What is the interval? 5 Minutes?

**Comment by topada** [comment]
unfortunately I can't find my then demon setup. I vaguely remember being very careful working with my timelapse setup, as it took images quite often. So i think it was **1 Frame / Minute** which roughly adds up ( 8,382 Frames / 103 hours = ~1 Frame / Minute )  It's not exact as I rounded the duration time.

**Comment by topada** [comment]
unfortunately I can't find my then demon setup. I vaguely remember being
very careful working with my timelapse setup, as it took images quite
often. So i think it was 1 Frame / Minute which roughly adds up ( 8,382
Frames / 103 hours = ~1 Frame / Minute ) It's not exact as I rounded the
duration time.

_––_
Jonas Köpfer

_topada *_design*
Schopenhauerstraße 16 14467 Potsdam *T *0173-8937295 koepfer@topada.de

**Comment by ff6347** [comment]
Aight. Thanks again
